apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: nodejs-rest-api
  name: nodejs-rest-api
  namespace: monitoring
spec: 
  ports: 
    - port: 3000
  selector: 
    app: nodejs-rest-api
  type: LoadBalancer
